# Generated by Django 6.0.1 on 2026-01-12 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="inspections/%Y/%m/%d/")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("GENUINE", "Genuine"),
                            ("SUSPICIOUS", "Suspicious"),
                            ("COUNTERFEIT", "Counterfeit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_inspections",
                        to="core.medicinelot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
