# Generated by Django 6.0.1 on 2026-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("verification_id", models.IntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
                ("block_number", models.IntegerField()),
                ("timestamp", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
