# Generated by Django 6.0.1 on 2026-01-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("vision", "0002_blockchainaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visioninspection",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inspections/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="visioninspection",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vision_inspections",
                to="core.medicinelot",
            ),
        ),
    ]
