# Generated by Django 6.0.1 on 2026-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0004_visioninspection_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="visioninspection",
            name="image_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
